---
- name: Apply ConfigMap resources
  k8s:
    apply: yes
    definition: "{{ lookup('template', 'eda.configmap.yaml.j2') }}"
    wait: yes

- name: Apply deployment resources
  k8s:
    apply: yes
    definition: "{{ lookup('template', item + '.yaml.j2') }}"
    wait: no
  loop:
    - 'eda-api.service'
    - 'eda-api.deployment'
    - 'eda-ui.service'
    - 'eda-ui.deployment'
    - 'eda-ui.ingress'
    - 'eda-default-worker.deployment'
    - 'eda-activation-worker.deployment'
    - 'eda-scheduler.deployment'

- name: Remove legacy EDA worker deployment
  k8s:
    api_version: apps/v1
    kind: Deployment
    name: "{{ ansible_operator_meta.name }}-worker"
    namespace: "{{ ansible_operator_meta.namespace }}"
    state: absent

- name: Check for API Pod
  k8s_info:
    kind: Pod
    api_version: v1
    namespace: "{{ ansible_operator_meta.namespace }}"
    label_selectors:
      - "app.kubernetes.io/name={{ ansible_operator_meta.name }}"
      - "app.kubernetes.io/managed-by={{ deployment_type }}-operator"
      - "app.kubernetes.io/component={{ deployment_type }}-api"
    field_selectors:
      - status.phase=Running
  register: eda_api_pod
  until:
    - "eda_api_pod['resources'] | length"
    - "eda_api_pod['resources'][0]['status']['phase'] == 'Running'"
    - "eda_api_pod['resources'][0]['status']['containerStatuses'][0]['ready'] == true"
    - "eda_api_pod['resources'][0]['status']['containerStatuses'][1]['ready'] == true"
  retries: 60
  delay: 5

- name: Set the resource pod name as a variable.
  set_fact:
    eda_api_pod_name: "{{ eda_api_pod['resources'][0]['metadata']['name'] | default('') }}"
