---

name: Build Operator Image

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    name: Push main image
    steps:
      - uses: actions/checkout@v2

      - name: Build Image
        run: |
          IMG=eda-server-operator:main make docker-buildx

      - name: Push To Quay
        uses: redhat-actions/push-to-registry@v2.1.1
        with:
          image: eda-server-operator
          tags: main
          registry: quay.io/ansible/
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}
