---

name: Build Operator Image

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    name: Push main image
    steps:
      - uses: actions/checkout@v2

      - name: Build Image
        run: |
          export PLATFORMS=linux/arm64,linux/amd64,linux/s390x,linux/ppc64le
          export IMG=eda-server-operator:main
          docker buildx create --name project-v3-builder
          docker buildx use project-v3-builder
          docker buildx build --push --platform=$(PLATFORMS) --tag ${IMG} -f Dockerfile .
          docker buildx rm project-v3-builder

      - name: Push To Quay
        uses: redhat-actions/push-to-registry@v2.1.1
        with:
          image: eda-server-operator
          tags: main
          registry: quay.io/ansible/
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}
